name: "kubewarden-check-policy-version"
description: "Check that policy version annotation is up-to-date"
branding:
  icon: "package"
  color: "blue"
inputs:
  expected-version:
    description: "The expected value of the version annotation. E.g: 0.1.0"
    required: true
  policy-working-dir:
    description: "working directory of the policy. Useful for repos with policies in folders"
    required: false
    default: .
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Check that io.kubewarden.policy.version annotation is up-to-date
      shell: bash
      working-directory: ${{ inputs.policy-working-dir }}
      run: |
        VERSION=$(grep 'io.kubewarden.policy.version' metadata.yml | awk '{print $2}' | tr -d '"')

        if [ "$VERSION" != "${{ inputs.expected-version }}" ]; then
          echo "The value of io.kubewarden.policy.version annotation is not in sync with the expected version: '${VERSION}' != '${{ inputs.expected-version }}'"
          exit 1
        fi
