name: "kubewarden-policy-gh-action-dependencies"
description: "Install all the binaries needed inside of GH action"
branding:
  icon: "package"
  color: "blue"
runs:
  using: "composite"
  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@398d4b0eeef1380460a10c8013a76f728fb906ac # v3.9.1
    - name: Install kwctl
      uses: kubewarden/github-actions/kwctl-installer@v4.5.2
    - name: Install bats
      run: sudo apt install -y bats
      shell: bash
    - name: Install SBOM generator tool
      uses: kubewarden/github-actions/sbom-generator-installer@v4.5.2
    - name: Install SBOM generator tool
      uses: kubewarden/github-actions/binaryen-installer@v4.5.2
