name: "kubewarden-policy-gh-action-dependencies"
description: "Install all the binaries needed inside of GH action"
branding:
  icon: "package"
  color: "blue"
runs:
  using: "composite"
  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0
    - name: Install kwctl
      uses: kubewarden/github-actions/kwctl-installer@v4.5.10
    - name: Install bats
      run: sudo apt install -y bats
      shell: bash
    - name: Install SBOM generator tool
      uses: kubewarden/github-actions/syft-installer@v4.5.10
    - name: Install binaryen tool
      uses: kubewarden/github-actions/binaryen-installer@v4.5.10
