name: "kubewarden-policy-gh-action-dependencies"
description: "Install all the binaries needed inside of GH action"
branding:
  icon: "package"
  color: "blue"
runs:
  using: "composite"
  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2
    - name: Install kwctl
      uses: kubewarden/github-actions/kwctl-installer@v4.5.7
    - name: Install bats
      run: sudo apt install -y bats
      shell: bash
    - name: Install SBOM generator tool
      uses: kubewarden/github-actions/syft-installer@v4.5.7
    - name: Install binaryen tool
      uses: kubewarden/github-actions/binaryen-installer@v4.5.7
