name: Tests and linters

on:
  workflow_call:
    secrets: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run tests
        uses: swiftwasm/swiftwasm-action@5f4ac6cd6d2273f0c6aba57d7281736428f0aeb7 # v5.9
        with:
          shell-action: carton test
