name: Tests and linters

on:
  workflow_call:
    secrets: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install npm
        run: npm install
      - name: Run unit-tests
        run: |
          make test
