name: Tests and linters

on:
  workflow_call:
    inputs:
      policy-working-dir:
        description: "working directory of the policy. Useful for repos with policies in folders"
        required: false
        type: string
        default: .
    secrets: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install opa
        uses: kubewarden/github-actions/opa-installer@v4.5.7
      - name: Run unit tests
        working-directory: ${{ inputs.policy-working-dir }}
        run: make test
