name: Tests and linters

on:
  workflow_call:
    secrets: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.4.4
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Install npm
        run: npm install
      - name: Run unit-tests
        run: |
          make test
